# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and tsconfig
COPY package*.json tsconfig.json ./

# Install dependencies (skip prepare scripts)
RUN npm install --ignore-scripts

# Copy source code
COPY src ./src
COPY README.md ./

# Build the project
RUN npm run build

# Expose port if needed (although using stdio transport so not necessary)

# Run the server
CMD ["npm", "start"]
